language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libboost-all-dev
before_script:
  - mkdir build
  - cd build
  - cmake -DVFSPP_BUILD_TESTS=ON ..
script: make test
