language: cpp
env:
  - BUILD_TYPE=Release GENERATOR=Ninja
  - BUILD_TYPE=Debug GENERATOR=Ninja
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y ninja-build
  - sudo apt-get install -qq boost1.54
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.2-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.2.2-Linux-x86_64.tar.gz
  - mkdir -p $HOME/cmake/
  - cp -fR cmake-3.2.2-Linux-x86_64/* $HOME/cmake/
before_script:
  - mkdir -p travis-build
  - cd travis-build
  - $HOME/cmake/bin/cmake -G "$GENERATOR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
script:
  - $HOME/cmake/bin/cmake --build .
  - $HOME/cmake/bin/cmake --build . --target run_tests
