language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake boost1.54
before_script:
  - mkdir build
  - cd build
  - cmake -DVFSPP_BUILD_TESTS=ON ..
script: make test
