language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev
before_script:
  - mkdir build
  - cd build
  - cmake -DVFSPP_BUILD_TESTS=ON ..
script: make test
